### ISSUE TITLE
remove pom.xml's

### ISSUE THREAD

**Issue by thombergs** [adessoAG/wicked-charts#120]
once the showcase build works

**Comment by anedomansky** [comment]
- removed all pom.xml files
- modified build.gradle in wicked-charts-showcase-wicket7
- modified build.gradle in showcase(parent)

wicked-charts-showcase-wicket7 now runs using Spring Boot. 

To build and run the showcase:
    gradlew.bat build wicked-charts-showcase-wicket7:bootRun
