### ISSUE TITLE
Unable to find highcharts wrapper when building showcase application using docs

### ISSUE THREAD

**Issue by jclaybaughMicron** [adessoAG/wicked-charts#139]
Here is the output from the command line: 

MacBook-Pro:wicked-charts-showcase-wicket7$ gradle build

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':wicked-charts-showcase-options:compileClasspath'.
> Could not find de.adesso.wicked-charts:highcharts-wrapper:3.0.0.
  Searched in the following locations:
      file:/Users/###/.m2/repository/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.pom
      file:/Users/###/.m2/repository/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.jar
      https://repo.maven.apache.org/maven2/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.pom
      https://repo.maven.apache.org/maven2/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.jar
      https://jcenter.bintray.com/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.pom
      https://jcenter.bintray.com/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.jar
      http://oss.jfrog.org/jcenter/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.pom
      http://oss.jfrog.org/jcenter/de/adesso/wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.jar
      http://oss.jfrog.org/jcenter/de.adesso.wicked-charts/highcharts-wrapper/ivy-3.0.0.xml
      http://oss.jfrog.org/jcenter/de.adesso.wicked-charts/highcharts-wrapper/3.0.0/highcharts-wrapper-3.0.0.jar
  Required by:
      project :wicked-charts-showcase-options

BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by SvenWirz** [comment]
We will look into it.

**Comment by anedomansky** [comment]
We are releasing version 3.0.0 soon... in the meantime you could build and run the showcase following these instructions:

1. Clone this Git repository again.(The repository was updated today)
2. Run gradle build publishToMavenLocal in the root directory of the project.
3. Run gradle build wicked-charts-showcase-wicket7:bootRun inside the showcase directory.
4. Go to localhost:8080 in a browser of your choice.

**Comment by jclaybaughMicron** [comment]
Process works and showcase loads correctly. It appears my misstep was not using the publishToMavenLocal target prior to running. Thanks for the information.
