### ISSUE TITLE
de.adesso.wicked-charts:wicked-charts-wicket8:3.0.0 missing from central repository?

### ISSUE THREAD

**Issue by VaclavC** [adessoAG/wicked-charts#149]
I cannot find wicked-charts in jcenter repository? Wanted to use it with Wicket 8...

**Comment by maximAtanasov** [comment]
Hello @VaclavC, a Wicket 8 module is available in wicked charts 3.1.0. That should fix the issue :)

**Comment by VaclavC** [comment]
Ah, thank you ;-). Perhaps an update of the readme would be nice. There is 3.0.0 version mentioned.
