### ISSUE TITLE
Problem with jQuery version

### ISSUE THREAD

**Issue by VaclavC** [adessoAG/wicked-charts#153]
It looks like I'll be very persistent here, please be patient ;-)

I'am trying to use wicked-charts alongside Kendo UI. Without charts I have loaded jQuery version 2.2.4. When I try to add a wicked chart, jQuery version 1.1.12 is loaded along with 2.2.4 version, which seems to break Kendo UI. I'am getting 'TypeError: jQuery(...).kendoMultiSelect is not a function' error then. 

Not sure, if it is problem of wicked-charts at all?

**Comment by maximAtanasov** [comment]
I have unfortunately never used Kendo UI. Are you using wicket-kendo-ui or some other setup?

**Comment by VaclavC** [comment]
I'am using wicket-kendo-ui.

**Comment by martin-g** [comment]
In YourApplication#init() add `getJavaScriptLibrarySettings().setJQueryReference(JQueryResourceReference.getV2())` (or something similar, I don't have it in front of me right now).

**Comment by maximAtanasov** [comment]
@martin-g 
Yes those are the proper methods, thanks. I tried including V2 along with wicked-charts and nothing seems broken, Hopefuly this works with kendo-ui. :)

**Comment by VaclavC** [comment]
V1 worked for me. Wicked-charts probably needs V1 and Kendo UI is able to work with both of them. Thank you.

If I understand it correctly, this forces using V1(23) everywhere in the application (except, at least, wicked-charts)?

**Comment by VaclavC** [comment]
Probably because wicked-charts somehow forces using of 1.12 version? And when I set everything else to use also V1, it works.

**Comment by maximAtanasov** [comment]
Wicked Charts shoudn't force that version on you. You can actually set the version used by the library using 
```
JavaScriptResourceRegistry.getInstance().setJQueryReference();
```

Maybe you could't try passing in V1 or V2 and see if that works.

**Comment by VaclavC** [comment]
If I set both of them

```
getJavaScriptLibrarySettings().setJQueryReference(JQueryResourceReference.getV1());
JavaScriptResourceRegistry.getInstance().setJQueryReference(JQueryResourceReference.getV1());
```

it works regardless of jQuery version used (even with V3). If I omit the second line, I must use V1 in the first.

**Comment by maximAtanasov** [comment]
I see, I seems then that the solutions would be to use the same jQuery version for both of them. :)

**Comment by VaclavC** [comment]
Yes. But you must take care about it. Without using these settings it does not work.

Perhaps it is worth of mentioning somewhere in the documentation?

**Comment by maximAtanasov** [comment]
Yes, This will be documented in the wiki.

**Comment by sebfz1** [comment]
About wicket-kendo-ui (8.x):

1. `KendoUIJavaScriptResourceReference` (for default/ASFv2 licensed widget) is relying on wicket's `JQueryPluginResourceReference` which gets the application's `jQueryReference` which is set to `V2` by default.
*But if the application does not exists at the stage it is called, then `JQueryResourceReference#get()` (deprecated) is called which returns `V1`*. See point 2.

2. If you added the "kendo-all" reference to your package, you may have used `KendoUILibrarySettings.get().setJavaScriptReference(new JQueryPluginResourceReference("kendo.all.min.js"));`. Like point 1, `V1` may be used if the application does not exits when it is called. **This would be the case if the statement was not in `MyApplication#init()`**

3. `JQueryUrlResourceReference` allows to specify the kendo-all js from the CDN for instance, like the preceding one, it gets the application's `jQueryReference` which is set to `V2` by default. But if the application does not exists, `V2` is returned in that case.

**Comment by martin-g** [comment]
Thank you for the clarifications, Sebastien!

> which gets the application's jQueryReference which is set to V2 by default.
> But if the application does not exists at the stage it is called, then JQueryResourceReference#get() (deprecated) is called which returns V1

This is surprising (for me!). I suggest to open a ticket for Wicket and change `#get()` to return V2 so it is consistent.

**Comment by sebfz1** [comment]
You're very welcome!
About `#get()`, I think I recall (a manner to say I'm really not sure) that it has been discussed and the decision was to keep it backward compatible, the time v2 becomes the reference. That's probably the reason why `get()` has been marked as deprecated. I will open a ticket to ask if the time has come to change :)

**Comment by maximAtanasov** [comment]
@VaclavC 
If the problem has been resolved for you, I will close this issue.

**Comment by VaclavC** [comment]
Sure. Thank you for your help.
