### ISSUE TITLE
InteractionBehavior.js is not bundled

### ISSUE THREAD

**Issue by logineimer** [adessoAG/wicked-charts#159]
Hello! I recently discovered an issue with your resource bundling in the final jar files. This [package](https://github.com/adessoAG/wicked-charts/tree/master/wicket/wicked-charts-wicket7/src/main/java/de/adesso/wickedcharts/wicket7/highcharts/features/interaction) contains an [InteractionBehavior.js](https://github.com/adessoAG/wicked-charts/tree/master/wicket/wicked-charts-wicket7/src/main/java/de/adesso/wickedcharts/wicket7/highcharts/features/interaction/InteractionBehavior.js) where the jars from JCenter seem not to contain this file. Ist there an issue with the build? 

Here's a screenshot of the artifact located in my local Maven repository. You can see that the JS is missing.

![wicked-charts](https://user-images.githubusercontent.com/3143217/43398223-b4cec946-9407-11e8-8400-3dd8d66e1f9f.JPG)

Best regards!

**Comment by maximAtanasov** [comment]
@logineimer 
Thanks for bringing this up, I haven't noticed that before. I will see what can be done to fix this.

**Comment by logineimer** [comment]
Thanks! Please keep in mind that I didn't check if this issue affects other resources as well.

**Comment by maximAtanasov** [comment]
I have fixed this in the latest snapshot release (as it turns out other files weren't showing up as well).  If you would like to use that, the correct dependency is in the README.  :)
