### ISSUE TITLE
ShowCase url for latest wicked-charts with chartjs is not working 

### ISSUE THREAD

**Issue by nikhilmalisetty** [adessoAG/wicked-charts#168]
https://wicked-charts-showcase.appspot.com/

Could you please check this and see if you can get the site up?
We need this for reference to create charts on our application

**Comment by maximAtanasov** [comment]
Hello,
Unfortunately the site seems to be getting more visitors than expected and so is sometimes offline. We'll see if we can fix that. In the meantime you can run the showcase locally by following these instructions: 

https://github.com/adessoAG/wicked-charts/wiki/Developer-Info:-Starting-the-Showcase-Application

**Comment by nikhilmalisetty** [comment]
> Hello,
> Unfortunately the site seems to be getting more visitors than expected and so is sometimes offline. We'll see if we can fix that. In the meantime you can run the showcase locally by following these instructions:
> 
> https://github.com/adessoAG/wicked-charts/wiki/Developer-Info:-Starting-the-Showcase-Application

Thanks a lot!

**Comment by maximAtanasov** [comment]
The website should be up for about a year now.
