### ISSUE TITLE
Add support for Highcharts contextButton

### ISSUE THREAD

**Issue by fabiocvalente** [adessoAG/wicked-charts#172]
I'm using highcharts-wrapper 3.1.0 to generate a JSON for Highcharts. I want to use the property `contextButton` of Highcharts https://api.highcharts.com/highcharts/exporting.buttons.contextButton because I just want the options to download PNG, JPG and PDF. I don't want the options to print or download as SVG.
On Highcharts documentation I can do that by definnig the property `exporting.buttons.contextButton.menuItems` as:
```
{
    exporting: {
        buttons: {
            contextButton: {
                menuItems: ["downloadPNG", "downloadPDF", "downloadJPEG"]
            }
        }
    }
}
```
I also want to use the other properties of `contextButton` such as `symbol`, `height`, `width`, `symbolX`, `symbolY`, `x` and `y`.
I didn't find how to do that with highcharts-wrapper classes. I googled it, look into the showcase, downloaded and searched the source code but still got nothing.
My impression/conclusion is that `contextButton` is not yet supported by highcharts-wrapper.
Then I would like to request the support for the Highcharts `contextButton` and its nested properties.
The workaround I came up with was to manualy set these properties in my JS code, but that is not very good because I have definition of the Highcharts object in two places, the Java code with most of the definition and thw JS code just for the `contextButton`.

**Comment by fabiocvalente** [comment]
Thanks @maximAtanasov 
Using 3.2.0-SNAPSHOT I could set `menuItems`, but the generated JSON is using the enum `name` instead of `value`.
This is the generated JSON
```
{
    exporting: {
        buttons: {
            contextButton: {
                enabled: true
                menuItems: [ "PRINT_CHART", "DOWNLOAD_JPEG", "DOWNLOAD_PNG"]
            }
        }
    }
}
```
According to the Highcharts documentation the generated JSON should be
```
{
    exporting: {
        buttons: {
            contextButton: {
                enabled: true
                menuItems: ["downloadPNG", "downloadPDF", "downloadJPEG"]
            }
        }
    }
}
```

**Comment by fabiocvalente** [comment]
I was looking at the source code and it seemed correct, there was no reason for that error.
After that I looked the commit and saw that you added a serializer `JsonValueEnumSerializer` for the interface `JsonValueEnum`.
I analysed my code and there was a custom serializer on my project. I removed the custom serializer and used your `JsonRenderer` and it worker just fine.

**Comment by maximAtanasov** [comment]
Great, I'm glad it works. I was just testing it again to make sure. :) I will see if I can update the wrapper for the latest Highcharts API later.
