### ISSUE TITLE
ZKoss implementation

### ISSUE THREAD

**Issue by thombergs** [adessoAG/wicked-charts#21]
Reported by maximilian.friedmann, Nov 4, 2013
Hi there,
many thanks for such a great HighCharts Wrapper. With 10 lines of code I managed to use it with the ZK framework together, maybe you can include this in further releases? 

``` java
package testing;

import org.zkoss.zk.ui.Component;
import org.zkoss.zk.ui.util.Clients;

import com.googlecode.wickedcharts.highcharts.jackson.JsonRenderer;
import com.googlecode.wickedcharts.highcharts.options.Options;


public class ZKWicketChart extends Options
{
    public void renderToComponent(final Component target)
    {
        getChartOptions().setRenderTo(target.getUuid());

        final JsonRenderer jsonRenderer = new JsonRenderer();
        final String json = jsonRenderer.toJson(this);

        Clients.evalJavaScript("new Highcharts.Chart(" + json + ");");
    }
}
```

**Comment by maximAtanasov** [comment]
I am closing this issue as it has been more than four years since any activity and also ZKoss now has it's now Chart library for web apps in java: 
https://www.zkoss.org/zkchartsdemo/
(Also using Highcharts)

So this is very much obsolete.
