### ISSUE TITLE
add support to maxPointWidth into PlotOptions -> column

### ISSUE THREAD

**Issue by benoitbb** [adessoAG/wicked-charts#76]
Hello,

Is it possible to add support to this option please ?

plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0,
                /* Here is the setting to limit the maximum column width. */
                maxPointWidth: 50
            }
        },

Thank you.

Regards,

**Comment by maximAtanasov** [comment]
Solved in PR #76 by @AyaAzzam
