### ISSUE TITLE
Support to configure minSize and maxSize for Bubble charts

### ISSUE THREAD

**Issue by sskjames** [adessoAG/wicked-charts#79]
Wicked charts should support configuring "minSize" and "maxSize" for Bubble plot options.
Ref: [Bubble Plot Options in HighCharts API](http://api.highcharts.com/highcharts/plotOptions.bubble.maxSize)

**Comment by fabiocvalente** [comment]
I'm using highcharts-wrapper **3.2.0-SNAPSHOT** to generate a JSON for Highcharts. I'm trying to configure the max size of the bubbles in a bubble graph. According to the Highcharts documentation in https://api.highcharts.com/highcharts/plotOptions.bubble.maxSize I have to use `plotOptions.bubble.maxSize` property, but I couldn't find that in the `PlotOptions` class.

**Comment by maximAtanasov** [comment]
Added in PR #174 by @fabiocvalente .
